# Generated by Django 4.0.5 on 2022-07-12 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_item', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 20, 29, 52, 547157)),
        ),
    ]
