# Generated by Django 4.0.5 on 2022-07-17 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 29, 19, 823212)),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 8, 29, 19, 824205)),
        ),
    ]
