# Generated by Django 4.0.5 on 2022-07-17 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 9, 56, 34, 502081)),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 9, 56, 34, 503080)),
        ),
    ]
