# Generated by Django 4.0.5 on 2022-07-17 03:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_wishlist_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 10, 0, 3, 474388)),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 10, 0, 3, 474388)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
