# Generated by Django 4.0.5 on 2022-07-17 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 10, 3, 18, 313323)),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 10, 3, 18, 314324)),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auctionlisting'),
        ),
    ]
