# Generated by Django 4.0.5 on 2022-07-18 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 11, 48, 57, 878291)),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 11, 48, 57, 878291)),
        ),
    ]
